from config import FILE_PATH, STAGE_NAME, TABLE_NAME

# Query to upload a file to Stage
UPLOAD_TO_STAGE_SQL = f"PUT file://{FILE_PATH} @{STAGE_NAME} AUTO_COMPRESS=FALSE OVERWRITE=TRUE;"

# Query to copy from Stage to RAW table
COPY_INTO_TABLE_SQL = f"""
    COPY INTO {TABLE_NAME} FROM @{STAGE_NAME}
    FILE_FORMAT = (TYPE = 'CSV', FIELD_DELIMITER = ',', SKIP_HEADER = 1, FIELD_OPTIONALLY_ENCLOSED_BY = '"')
    ON_ERROR = 'ABORT_STATEMENT'
    FORCE = TRUE;
"""

# Call procedures
CALL_CORE_PROC_SQL = "CALL AIRLINE_DWH.CORE.LOAD_CORE_LAYER();"
CALL_MARTS_PROC_SQL = "CALL AIRLINE_DWH.MARTS.LOAD_MARTS_LAYER();"