-- INITIAL SETUP (DB, SCHEMAS, RAW)
CREATE DATABASE IF NOT EXISTS AIRLINE_DWH;
USE DATABASE AIRLINE_DWH;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS MARTS;


-- Create RAW table
CREATE OR REPLACE TABLE AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_RAW (
    "CSV_Row_Index" VARCHAR, 
    "Passenger ID" VARCHAR,
    "First Name" VARCHAR,
    "Last Name" VARCHAR,
    "Gender" VARCHAR,
    "Age" VARCHAR,
    "Nationality" VARCHAR,
    "Airport Name" VARCHAR,
    "Airport Country Code" VARCHAR,
    "Country Name" VARCHAR,
    "Airport Continent" VARCHAR,
    "Continents" VARCHAR,
    "Departure Date" VARCHAR,
    "Arrival Airport" VARCHAR,
    "Pilot Name" VARCHAR,
    "Flight Status" VARCHAR,
    "Ticket Type" VARCHAR,
    "Passenger Status" VARCHAR
);


-- Create Stage for file upload
CREATE OR REPLACE STAGE AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STAGE
    FILE_FORMAT = (
        TYPE = 'CSV',
        FIELD_DELIMITER = ',',
        SKIP_HEADER = 1,
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    );


-- Create Stream for CDC
CREATE OR REPLACE STREAM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM 
ON TABLE AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_RAW;

SHOW STREAMS;
SELECT * FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM order by "CSV_Row_Index" desc LIMIT 100;


-- CORE LAYER (NORMALIZED TABLES)
-- Normalized Tables with surrogate keys and audit columns
USE SCHEMA AIRLINE_DWH.CORE;
CREATE OR REPLACE TABLE PASSENGERS (
    PASSENGER_ID VARCHAR PRIMARY KEY,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE NUMBER,
    NATIONALITY VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AIRPORTS (
    AIRPORT_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    AIRPORT_NAME VARCHAR,
    COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    CONTINENT VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE PILOTS (
    PILOT_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    PILOT_NAME VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FLIGHTS (
    FLIGHT_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    PASSENGER_ID VARCHAR,
    AIRPORT_ID NUMBER,
    PILOT_ID NUMBER,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT_CODE VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS(PASSENGER_ID),
    FOREIGN KEY (AIRPORT_ID) REFERENCES AIRPORTS(AIRPORT_ID),
    FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(PILOT_ID)
);


-- Stored Procedure: ELT Process (RAW -> CORE)
CREATE OR REPLACE PROCEDURE AIRLINE_DWH.CORE.LOAD_CORE_LAYER()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    total_rows_inserted INTEGER DEFAULT 0;
BEGIN
    BEGIN TRANSACTION;

    -- Load Dimensions (Deduplication using NOT EXISTS)
    INSERT INTO AIRLINE_DWH.CORE.PASSENGERS (PASSENGER_ID, FIRST_NAME, LAST_NAME, GENDER, AGE, NATIONALITY)
    SELECT DISTINCT "Passenger ID", "First Name", "Last Name", "Gender", TRY_TO_NUMBER("Age"), "Nationality"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM s
    WHERE NOT EXISTS (SELECT 1 FROM AIRLINE_DWH.CORE.PASSENGERS p WHERE p.PASSENGER_ID = s."Passenger ID");
    
    total_rows_inserted := total_rows_inserted + SQLROWCOUNT;


    INSERT INTO AIRLINE_DWH.CORE.AIRPORTS (AIRPORT_NAME, COUNTRY_CODE, COUNTRY_NAME, CONTINENT)
    SELECT DISTINCT "Airport Name", "Airport Country Code", "Country Name", "Airport Continent"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM s
    WHERE NOT EXISTS (SELECT 1 FROM AIRLINE_DWH.CORE.AIRPORTS a WHERE a.AIRPORT_NAME = s."Airport Name");
    
    total_rows_inserted := total_rows_inserted + SQLROWCOUNT;


    INSERT INTO AIRLINE_DWH.CORE.PILOTS (PILOT_NAME)
    SELECT DISTINCT "Pilot Name"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM s
    WHERE NOT EXISTS (SELECT 1 FROM AIRLINE_DWH.CORE.PILOTS p WHERE p.PILOT_NAME = s."Pilot Name");
    
    total_rows_inserted := total_rows_inserted + SQLROWCOUNT;


    INSERT INTO AIRLINE_DWH.CORE.FLIGHTS (PASSENGER_ID, AIRPORT_ID, PILOT_ID, DEPARTURE_DATE, ARRIVAL_AIRPORT_CODE, 
        FLIGHT_STATUS, TICKET_TYPE, PASSENGER_STATUS)
    SELECT 
        s."Passenger ID", 
        a.AIRPORT_ID, 
        p.PILOT_ID, 
        TRY_TO_DATE(s."Departure Date", 'MM/DD/YYYY'), 
        s."Arrival Airport", 
        s."Flight Status", 
        s."Ticket Type", 
        s."Passenger Status"
    FROM AIRLINE_DWH.RAW.AIRLINE_FLIGHTS_STREAM s
    LEFT JOIN AIRLINE_DWH.CORE.AIRPORTS a ON s."Airport Name" = a.AIRPORT_NAME
    LEFT JOIN AIRLINE_DWH.CORE.PILOTS p ON s."Pilot Name" = p.PILOT_NAME;
    
    total_rows_inserted := total_rows_inserted + SQLROWCOUNT;

    -- Log Success
    INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, LAYER_NAME, ROWS_AFFECTED, STATUS, MESSAGE)
    VALUES ('LOAD_CORE_LAYER', 'CORE', :total_rows_inserted, 'SUCCESS', 'Data loaded successfully');

    COMMIT;
    RETURN 'Success: Data loaded into CORE. Rows: ' || :total_rows_inserted;

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RETURN 'FAILURE: ' || SQLERRM;
END;
$$;

-- MARTS LAYER (AGGREGATIONS)
USE SCHEMA AIRLINE_DWH.MARTS;
CREATE OR REPLACE TABLE DAILY_AIRPORT_STATS (
    REPORT_DATE DATE,
    AIRPORT_NAME VARCHAR,
    COUNTRY_NAME VARCHAR,
    TOTAL_FLIGHTS NUMBER,
    UNIQUE_PILOTS NUMBER,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Stored Procedure: Aggregation (CORE -> MARTS)
CREATE OR REPLACE PROCEDURE LOAD_MARTS_LAYER()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    rows_inserted INTEGER DEFAULT 0;
BEGIN
    BEGIN TRANSACTION;

    -- Full Refresh Strategy
    TRUNCATE TABLE AIRLINE_DWH.MARTS.DAILY_AIRPORT_STATS;

    INSERT INTO AIRLINE_DWH.MARTS.DAILY_AIRPORT_STATS 
    (REPORT_DATE, AIRPORT_NAME, COUNTRY_NAME, TOTAL_FLIGHTS, UNIQUE_PILOTS)
    SELECT 
        f.DEPARTURE_DATE,
        a.AIRPORT_NAME,
        a.COUNTRY_NAME,
        COUNT(f.FLIGHT_ID) as TOTAL_FLIGHTS,
        COUNT(DISTINCT f.PILOT_ID) as UNIQUE_PILOTS
    FROM AIRLINE_DWH.CORE.FLIGHTS f
    JOIN AIRLINE_DWH.CORE.AIRPORTS a ON f.AIRPORT_ID = a.AIRPORT_ID
    GROUP BY 1, 2, 3;

    rows_inserted := SQLROWCOUNT;
    INSERT INTO AIRLINE_DWH.CORE.AUDIT_LOG (PROCEDURE_NAME, LAYER_NAME, ROWS_AFFECTED, STATUS, MESSAGE)
    VALUES ('LOAD_MARTS_LAYER', 'MARTS', :rows_inserted, 'SUCCESS', 'Marts refreshed successfully');

    COMMIT;
    RETURN 'Success: Marts loaded.';

EXCEPTION
    WHEN OTHER THEN
        ROLLBACK;
        RETURN 'FAILURE: ' || SQLERRM;
END;
$$;


-- Create Audit Table for logging
USE SCHEMA AIRLINE_DWH.CORE;
CREATE OR REPLACE TABLE AUDIT_LOG (
    LOG_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    LOG_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROCEDURE_NAME VARCHAR,
    LAYER_NAME VARCHAR,
    ROWS_AFFECTED NUMBER,
    STATUS VARCHAR,
    MESSAGE VARCHAR
);


-- ADVANCED FEATURES
-- Time Travel Demo (DDL/DML)
CREATE TABLE AIRLINE_DWH.CORE.FLIGHTS_BACKUP CLONE AIRLINE_DWH.CORE.FLIGHTS;
DROP TABLE AIRLINE_DWH.CORE.FLIGHTS_BACKUP;
UNDROP TABLE AIRLINE_DWH.CORE.FLIGHTS_BACKUP;

SET MY_TIMESTAMP = CURRENT_TIMESTAMP();
UPDATE AIRLINE_DWH.CORE.FLIGHTS_BACKUP 
SET FLIGHT_STATUS = 'Delayed' 
WHERE FLIGHT_STATUS = 'On Time';


-- Verify Time Travel
SELECT COUNT(*) FROM AIRLINE_DWH.CORE.FLIGHTS_BACKUP WHERE FLIGHT_STATUS = 'On Time';
SELECT COUNT(*) FROM AIRLINE_DWH.CORE.FLIGHTS_BACKUP AT(TIMESTAMP => $MY_TIMESTAMP) WHERE FLIGHT_STATUS = 'On Time';


-- Security: Row Level Security
USE SCHEMA AIRLINE_DWH.CORE;
CREATE OR REPLACE TABLE SECURITY_MAPPING (
    ROLE_NAME VARCHAR,
    ALLOWED_COUNTRY VARCHAR
);
INSERT INTO SECURITY_MAPPING (ROLE_NAME, ALLOWED_COUNTRY)
VALUES ('ACCOUNTADMIN', 'United States');

USE SCHEMA AIRLINE_DWH.MARTS;
CREATE OR REPLACE SECURE VIEW FACT_FLIGHTS_SECURE AS
SELECT 
    f.*, 
    a.COUNTRY_NAME
FROM AIRLINE_DWH.CORE.FLIGHTS f
JOIN AIRLINE_DWH.CORE.AIRPORTS a ON f.AIRPORT_ID = a.AIRPORT_ID
WHERE a.COUNTRY_NAME IN (
    SELECT ALLOWED_COUNTRY 
    FROM AIRLINE_DWH.CORE.SECURITY_MAPPING 
    WHERE ROLE_NAME = CURRENT_ROLE()
);

SELECT DISTINCT COUNTRY_NAME FROM AIRLINE_DWH.MARTS.FACT_FLIGHTS_SECURE;